### ISSUE TITLE
Listbox - Fix scoll when mouseover focus is triggered

### ISSUE THREAD

**Issue by VirajS00** [lxsmnsyc/terracotta#37]
hello,
I'm using the listbox and here is an issue I found:

When there is a scroll in the listbox options and the user mouseovers it, there should be no scroll (as in the video below).

https://github.com/user-attachments/assets/91630e2e-c118-4d5e-8be5-55baa74a1fc6

p.s. There is a simple fix for this, can I create a PR?

Awesome Library though!

**Comment by lxsmnsyc** [comment]
You can create a PR. Although based on the video, I think this is a browser behavior.

**Comment by VirajS00** [comment]
When you do the `el.focus()` on mouseenter, you can provide one options, `el.focus({ preventScroll: true })`, this will fix the issue.

**Comment by VirajS00** [comment]
Here is the PR for this issue: https://github.com/lxsmnsyc/terracotta/pull/38

**Comment by lxsmnsyc** [comment]
> When you do the el.focus() on mouseenter, you can provide one option, el.focus({ preventScroll: true }), this will fix the issue.

ah that's an interesting solution, somehow I missed that. Thanks!

**Comment by VirajS00** [comment]
Thanks for this library, it's awesome!
